name: dsfin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - xgboost
  - gdown
  - dvc
  - boto3
  - jupyter
  - pip
  - tensorflow
  - keras